on:
  push:

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      packages: write
      contents: read
      checks: read

    steps:
      - uses: actions/checkout@v4

      # setup jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: run test
        run: |
          mvn verify -Dvaadin.offlineKey="${{secrets.VAADIN_OFFLINE_KEY}}" -Pit -B -T 4C --no-transfer-progress
